// Test script pour vérifier l'export PDF
console.log('🧪 Début des tests PDF...');

// Test 1: Vérifier que jsPDF se charge
setTimeout(() => {
    console.log('📦 Test 1: Vérification jsPDF');
    if (typeof window.jspdf !== 'undefined') {
        console.log('✅ jsPDF chargé avec succès');
        console.log('📋 Version jsPDF:', window.jspdf.version || 'inconnue');
    } else {
        console.error('❌ jsPDF non trouvé');
        return;
    }

    // Test 2: Simuler la génération de texte
    console.log('📝 Test 2: Simulation génération de texte');
    const outputElement = document.querySelector('.typewriter-output');
    if (outputElement) {
        outputElement.innerHTML = `
            <span class="char-faded">T</span>his is a test document generated by CrazyTyper.

            It contains multiple paragraphs with typewriter effects like <span class="char-heavy">bold characters</span>, 
            <span class="char-faded">faded text</span>, and <span class="char-uneven">uneven spacing</span>.

            This should demonstrate how the PDF export handles different text formatting and 
            typewriter imperfections in the final output.

            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor 
            incididunt ut labore et dolore magna aliqua.
        `;
        outputElement.style.display = 'block';
        document.getElementById('outputSection').classList.remove('hidden');
        console.log('✅ Texte test ajouté à l\'output');
    } else {
        console.error('❌ Element output non trouvé');
    }

    // Test 3: Vérifier les polices disponibles
    console.log('🔤 Test 3: Polices disponibles');
    const fontSelect = document.getElementById('fontSelect');
    if (fontSelect) {
        console.log('✅ Font select trouvé avec', fontSelect.options.length, 'options');
        
        // Test avec une police typewriter
        fontSelect.value = 'jmh-typewriter';
        console.log('🎯 Police sélectionnée:', fontSelect.value);
    }

    // Test 4: Test export PDF
    console.log('🔄 Test 4: Test export PDF...');
    setTimeout(() => {
        try {
            exportToPDF();
            console.log('✅ Export PDF déclenché sans erreur');
        } catch (error) {
            console.error('❌ Erreur export PDF:', error);
        }
    }, 1000);

}, 2000); // Attendre que tout se charge

// Test des polices après chargement
setTimeout(() => {
    console.log('🔍 Test bonus: Vérification polices custom');
    const computedStyle = window.getComputedStyle(document.querySelector('.typewriter-output'));
    console.log('📋 Police calculée:', computedStyle.fontFamily);
}, 3000);

console.log('⏳ Tests en cours... Vérifiez la console dans 5 secondes');